name: Cypress Tests

on:    
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    install:
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Cypress install
          uses: cypress-io/gitgub-action@v6
          with:
            runTests: false
            build: npm run build
        
        - name: Install dependencies
          run: npm ci
          
        - name: Save build folder
          uses: actions/upload-artifact@v4
          with:
            name: build
            if-no-files-found: error
            path: build

    cypress-run:
        runs-on: ubuntu-24.04
        env:
            VITE_API_URL: ${{ secrets.VITE_URL_API }}
            CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Start json-server
              run: npx json-server --watch data/db.json --port 3000 &

            - name: Wait for json-server
              run: npx wait-on ${{ secrets.VITE_API_URL }}

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                start: npm run preview
                browser: chrome
                record: true