name: Cypress Tests

on:    
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    cypress:
        runs-on: ubuntu-24.04
        env:
            VITE_API_URL: ${{ secrets.VITE_URL_API }}
            CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Cypress Tests
              uses: cypress-io/github-action@v6
              with:
                command: npm run launchapi
                build: npm run build
                start: npm run preview
                record: true