name: Lint

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    eslint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
            - run: npm ci
            - uses: sibiraj-s/action-eslint@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                working-directory: src
                package-manager: npm